[phases.setup]
# أضفنا 'mysql-client' لنتمكن من التعامل مع MySQL إذا لزم الأمر
nixPkgs = ['php83', 'php83Packages.composer', 'nodejs', 'npm', 'mysql-client']

[phases.build]
dependsOn = ['install']
cmds = [
    'composer install --no-interaction --optimize-autoloader',
    'npm install',
    'npm run build',
    'php artisan migrate --force',
    'php artisan optimize'
]

[phases.start]
cmd = 'php artisan serve --host 0.0.0.0 --port $PORT'
